# Generated by Django 5.1 on 2026-06-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Автори'},
        ),
    ]
