# Generated by Django 5.1 on 2026-06-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_orderitem_options_alter_book_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
